### ISSUE TITLE
App/UI Crashed

### ISSUE THREAD

**Issue by muctebanesiri** [polymorphicshade/Tubular#155]
Every time I minimize the app and reopen it the app crashes.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.27.2
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = org.schabi.newpipe.extractor.channel.ChannelInfo)
	at android.os.Parcel.writeSerializable(Parcel.java:2166)
	at android.os.Parcel.writeValue(Parcel.java:1932)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1024)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1304)
	at android.os.Parcel.writeBundle(Parcel.java:1093)
	at android.os.Parcel.writeValue(Parcel.java:1850)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1024)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1304)
	at android.os.Parcel.writeBundle(Parcel.java:1093)
	at android.os.Parcel.writeValue(Parcel.java:1850)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1024)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1304)
	at android.os.Parcel.writeBundle(Parcel.java:1093)
	at android.os.Parcel.writeValue(Parcel.java:1850)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1024)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1304)
	at android.os.Parcel.writeBundle(Parcel.java:1093)
	at androidx.fragment.app.Fragment$SavedState.writeToParcel(Fragment.java:542)
	at android.os.Parcel.writeParcelable(Parcel.java:1953)
	at android.os.Parcel.writeValue(Parcel.java:1859)
	at android.os.Parcel.writeList(Parcel.java:1141)
	at android.os.Parcel.writeValue(Parcel.java:1881)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1024)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1304)
	at android.os.Parcel.writeParcelable(Parcel.java:1953)
	at androidx.viewpager.widget.ViewPager$SavedState.writeToParcel(ViewPager.java:1402)
	at android.os.Parcel.writeParcelable(Parcel.java:1953)
	at android.os.Parcel.writeValue(Parcel.java:1859)
	at android.os.Parcel.writeSparseArray(Parcel.java:1181)
	at android.os.Parcel.writeValue(Parcel.java:1884)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1024)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1304)
	at android.os.Parcel.writeBundle(Parcel.java:1093)
	at android.os.Parcel.writeValue(Parcel.java:1850)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1024)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1304)
	at android.os.Parcel.writeBundle(Parcel.java:1093)
	at android.os.Parcel.writeValue(Parcel.java:1850)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1024)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1304)
	at android.os.Parcel.writeBundle(Parcel.java:1093)
	at android.os.Parcel.writeValue(Parcel.java:1850)
	at android.os.BaseBundle.dumpStats(BaseBundle.java:1690)
	at android.os.BaseBundle.dumpStats(BaseBundle.java:1727)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:150)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8322)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
Caused by: java.io.NotSerializableException: org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at java.util.ArrayList.writeObject(ArrayList.java:762)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1036)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1552)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at android.os.Parcel.writeSerializable(Parcel.java:2161)
	... 60 more

```
</details>
<hr>

**Comment by VitoItalianGamer** [comment]
I have the same issue too.

**Comment by ABJ4403** [comment]
I didn't experience this, could you tell how to reproduce it exactly? or maybe its random??

**Comment by asandikci** [comment]
Could you reproduce it with newpipe 27.3 version?

**Comment by elfinvale** [comment]
i also have experienced this. it happens in a few situations; i can most reliability reproduce it by trying to open the **first** channel in my Subscriptions list in Firefox, using the android "Share" feature. i can't reproduce it in vanilla NewPipe.

here's the log:

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ AU
* __Content Language:__ en-AU
* __App Language:__ en_AU
* __Service:__ none
* __Version:__ 0.27.2
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = org.schabi.newpipe.extractor.channel.ChannelInfo)
	at android.os.Parcel.writeSerializable(Parcel.java:2212)
	at android.os.Parcel.writeValue(Parcel.java:1978)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1070)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1304)
	at android.os.Parcel.writeBundle(Parcel.java:1139)
	at android.os.Parcel.writeValue(Parcel.java:1896)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1070)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1304)
	at android.os.Parcel.writeBundle(Parcel.java:1139)
	at android.os.Parcel.writeValue(Parcel.java:1896)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1070)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1304)
	at android.os.Parcel.writeBundle(Parcel.java:1139)
	at android.os.Parcel.writeValue(Parcel.java:1896)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1070)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1304)
	at android.os.Parcel.writeBundle(Parcel.java:1139)
	at android.os.Parcel.writeValue(Parcel.java:1896)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1070)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1304)
	at android.os.Parcel.writeBundle(Parcel.java:1139)
	at android.os.Parcel.writeValue(Parcel.java:1896)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1070)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1304)
	at android.os.Parcel.writeBundle(Parcel.java:1139)
	at android.os.Parcel.writeValue(Parcel.java:1896)
	at android.os.BaseBundle.dumpStats(BaseBundle.java:1690)
	at android.os.BaseBundle.dumpStats(BaseBundle.java:1727)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:150)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8249)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)
Caused by: java.io.NotSerializableException: org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at java.util.ArrayList.writeObject(ArrayList.java:955)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1079)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1568)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at android.os.Parcel.writeSerializable(Parcel.java:2207)
	... 42 more

```
</details>
<hr>

**Comment by asandikci** [comment]
Could you please test with latest release?

**Comment by asandikci** [comment]
closing then, you can request re-open if issue persist
