### ISSUE TITLE
Videos not loading

### ISSUE THREAD

**Issue by Dakkaron** [polymorphicshade/Tubular#163]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/Tubular/releases/latest).
- [X] I am *not* able to reproduce the bug with the *latest version* of [vanilla NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/Tubular/issues) or [closed](https://github.com/polymorphicshade/Tubular/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the vanilla NewPipe [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.2

### Steps to reproduce the bug

1. Open any video

### Expected behavior

Video should play 

### Actual behavior

Guru meditation

### Logs

```
## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=XnkQKn67qzM
* __Content Country:__ AT
* __Content Language:__ de-AT
* __App Language:__ de_AT
* __Service:__ YouTube
* __Version:__ 0.27.2
* __OS:__ Linux Android 14 - 34
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ExtractionException: IOS player response is not valid
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.fetchIosMobileJsonPlayer(YoutubeStreamExtractor.java:967)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:823)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:60)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:97)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:89)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:123)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$vk-P1AIrAksLBYlI0isZpDsAT7I(ExtractorHelper.java:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda11.call(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

```
</details>
<hr>
```

### Affected Android/Custom ROM version

Android 14, stock

### Affected device model

Samsung Galaxy A54

### Additional information

Tested and not reproduced in NewPipe 0.27.2.

**Comment by ABJ4403** [comment]
This happened on me too, after that it comes up w/ error "You must login to prove you are not a bot" :(

Well this is NewPipe issue, and not Tubular issue, in fact there's pinned issue there mentioning exactly about this (but not the IOS error)

**Comment by asandikci** [comment]
#192 is duplicate of this issue. Closing this because other issue has more information Either this will be solved with next release
