### ISSUE TITLE
Video not playing in full screen mode 

### ISSUE THREAD

**Issue by JustRandomboy** [polymorphicshade/Tubular#185]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/Tubular/releases/latest).
- [X] I am *not* able to reproduce the bug with the *latest version* of [vanilla NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/Tubular/issues) or [closed](https://github.com/polymorphicshade/Tubular/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the vanilla NewPipe [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.2

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_DECODING_FAILED] occurred while playing https://www.youtube.com/watch?v=0zdhWR0pPiA
* __Content Country:__ IN
* __Content Language:__ en-IN
* __App Language:__ en_IN
* __Service:__ YouTube
* __Version:__ 0.27.2
* __OS:__ Linux Android 15 - 35
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(140, null, null, audio/mp4a-latm, mp4a.40.2, 131541, en, [-1, -1, -1.0], [2, 44100]), format_supported=YES
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:578)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecDecoderException: Decoder failed: c2.android.aac.decoder
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.createDecoderException(MediaCodecRenderer.java:936)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:803)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1007)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:502)
	... 4 more
Caused by: android.media.MediaCodec$CodecException: Error 0xffffffe0

```
</details>
<hr>

### Screenshots/Recordings

Uploading InShot_20241226_221309825.mp4…

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_DECODING_FAILED] occurred while playing https://www.youtube.com/watch?v=0zdhWR0pPiA
* __Content Country:__ IN
* __Content Language:__ en-IN
* __App Language:__ en_IN
* __Service:__ YouTube
* __Version:__ 0.27.2
* __OS:__ Linux Android 15 - 35
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(140, null, null, audio/mp4a-latm, mp4a.40.2, 131541, en, [-1, -1, -1.0], [2, 44100]), format_supported=YES
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:578)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecDecoderException: Decoder failed: c2.android.aac.decoder
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.createDecoderException(MediaCodecRenderer.java:936)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:803)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1007)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:502)
	... 4 more
Caused by: android.media.MediaCodec$CodecException: Error 0xffffffe0

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 15 

### Affected device model

Redmi note 9

**Comment by asandikci** [comment]
Could you try to change exoplayer settings please. 

`Settings > Video and Audio > Exoplayer settings`

Maybe `Disable media tunneling` and `Always use ExoPlayer's video output surface setting workaround` settings can solve the issue

Also you can try with changing default resolution to lower(or another) value

**Comment by JustRandomboy** [comment]
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ IN
* __Content Language:__ en-IN
* __App Language:__ en_IN
* __Service:__ none
* __Version:__ 0.27.2
* __OS:__ Linux Android 15 - 35
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to write to field 'android.view.ViewParent android.view.View.mParent' on a null object reference in method 'void android.view.ViewGroup.removeFromArray(int)'
	at android.view.ViewGroup.removeFromArray(ViewGroup.java:5393)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5590)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5552)
	at android.view.ViewGroup.removeView(ViewGroup.java:5483)
	at org.schabi.newpipe.player.ui.MainPlayerUi.removeViewFromParent(MainPlayerUi.java:227)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$tryAddVideoPlayerView$41(VideoDetailFragment.java:1326)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.$r8$lambda$s-YSZ_fvw5kK3nBMjl4uKoby47w(VideoDetailFragment.java:0)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$$ExternalSyntheticLambda74.accept(R8$$SyntheticClass:0)
	at j$.util.Optional.ifPresent(Unknown Source:4)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$tryAddVideoPlayerView$42(VideoDetailFragment.java:1322)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.$r8$lambda$S8n3OzU8HWJ8m_WwgX_142JT8Zo(VideoDetailFragment.java:0)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$$ExternalSyntheticLambda60.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8705)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)

```
</details>
<hr>

**Comment by JustRandomboy** [comment]
New error after doing the settings

**Comment by asandikci** [comment]
- Could you try after clearing application cache (not data, otherwise you will lost your data. You have been warned)

- Maybe you can try all combination of these toggles 
(see: https://github.com/TeamNewPipe/NewPipe/issues/11329 )

- Also because you are using the latest android version **maybe** the version 27.2 have a specific issue. Could you please try with the latest NewPipe version

**Comment by JustRandomboy** [comment]
Working u can close  this 👍

**Comment by asandikci** [comment]
No problem. I am not a collaborator in this repo so could not close this issue. Probably you can.

And could you please tell what did solved your issue? It would be good if someone has similar issue.
