### ISSUE TITLE
Comment section is broken

### ISSUE THREAD

**Issue by Tech-e1** [polymorphicshade/Tubular#45]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/Tubular/releases/latest).
- [X] I am *not* able to reproduce the bug with the *latest version* of [vanilla NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/Tubular/issues) or [closed](https://github.com/polymorphicshade/Tubular/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the vanilla NewPipe [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.26.1r3

### Steps to reproduce the bug

1. Open video 
2. Slide to comment section

### Expected behavior

What is expected is that once the comments tab is tapped or swiped that comments load properly

### Actual behavior

An error report develops and no comments populate

### Screenshots/Recordings

![Screenshot_20240330-205638_Tubular](https://github.com/polymorphicshade/Tubular/assets/99435218/cb8c01c9-779a-4751-9ced-6fbb6bca4f38)

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.26.1_r3
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Failure from system
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1845)
	at android.app.Activity.startActivityForResult(Activity.java:5507)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:712)
	at android.app.Activity.startActivityForResult(Activity.java:5465)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:693)
	at android.app.Activity.startActivity(Activity.java:5963)
	at android.app.Activity.startActivity(Activity.java:5930)
	at org.schabi.newpipe.error.ErrorUtil$Companion.openActivity(ErrorUtil.kt:43)
	at org.schabi.newpipe.error.ErrorUtil$Companion.showSnackbar$lambda$0(ErrorUtil.kt:149)
	at org.schabi.newpipe.error.ErrorUtil$Companion.$r8$lambda$hbVLiP6-HtFc17h3_yyNDsmaIY8(ErrorUtil.kt:0)
	at org.schabi.newpipe.error.ErrorUtil$Companion$$ExternalSyntheticLambda0.onClick(R8$$SyntheticClass:0)
	at com.google.android.material.snackbar.Snackbar.lambda$setAction$0(Snackbar.java:352)
	at com.google.android.material.snackbar.Snackbar.$r8$lambda$4rINiMZz55Dc47hSTCuz-ALWyEw(Snackbar.java:0)
	at com.google.android.material.snackbar.Snackbar$$ExternalSyntheticLambda1.onClick(R8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:7542)
	at android.view.View.performClickInternal(View.java:7519)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29476)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: android.os.TransactionTooLargeException: data parcel size 1242032 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:584)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2069)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1838)
	... 25 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 13/ eOS v1.21

### Affected device model

Moto G7 power (ocean)

**Comment by polymorphicshade** [comment]
This is a well-known issue in vanilla NewPipe. This will not be fixed until the NewPipe devs publish a fix.

**Comment by BurnyBoi** [comment]
FYI the fix should be in NewPipe: https://github.com/TeamNewPipe/NewPipeExtractor/pull/1163

**Comment by LeeBinder** [comment]
[NewPipe Release v0.27.0 (please TEST!) #10930](https://github.com/TeamNewPipe/NewPipe/issues/10930)

**Comment by pslyman** [comment]
It's now in a new release from 1 day ago: https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.27.0
