### ISSUE TITLE
App/UI crashed when reporting

### ISSUE THREAD

**Issue by mrkrabs206** [polymorphicshade/Tubular#49]
### Checklist

- [x] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/Tubular/releases/latest).
- [X] I am *not* able to reproduce the bug with the *latest version* of [vanilla NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/Tubular/issues) or [closed](https://github.com/polymorphicshade/Tubular/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the vanilla NewPipe [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.26.1_r3

### Steps to reproduce the bug

Open NewPipe or Tubular
Go to a video
When error shows, press REPORT
Crashes

### Expected behavior

After pressing REPORT, it should show up a reporting screen with the error.

### Actual behavior

After pressing report, the app crashes and it shows app/ui crashed.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.26.1_r3
* __OS:__ Linux Android 14 - 34
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Failure from system
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1882)
	at android.app.Activity.startActivityForResult(Activity.java:5589)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:712)
	at android.app.Activity.startActivityForResult(Activity.java:5547)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:693)
	at android.app.Activity.startActivity(Activity.java:6045)
	at android.app.Activity.startActivity(Activity.java:6012)
	at org.schabi.newpipe.error.ErrorUtil$Companion.openActivity(ErrorUtil.kt:43)
	at org.schabi.newpipe.error.ErrorUtil$Companion.showSnackbar$lambda$0(ErrorUtil.kt:149)
	at org.schabi.newpipe.error.ErrorUtil$Companion.$r8$lambda$hbVLiP6-HtFc17h3_yyNDsmaIY8(ErrorUtil.kt:0)
	at org.schabi.newpipe.error.ErrorUtil$Companion$$ExternalSyntheticLambda0.onClick(R8$$SyntheticClass:0)
	at com.google.android.material.snackbar.Snackbar.lambda$setAction$0(Snackbar.java:352)
	at com.google.android.material.snackbar.Snackbar.$r8$lambda$4rINiMZz55Dc47hSTCuz-ALWyEw(Snackbar.java:0)
	at com.google.android.material.snackbar.Snackbar$$ExternalSyntheticLambda1.onClick(R8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:7670)
	at android.view.View.performClickInternal(View.java:7644)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30175)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8223)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)
Caused by: android.os.TransactionTooLargeException: data parcel size 1179968 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:584)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2214)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1875)
	... 25 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 14 (65.2.A.2.137)

### Affected device model

Sony Xperia 10 IV (XQ-CC54)

### Additional information

Reporting system broken

**Comment by AMZBoss215** [comment]
The same happened with me recently
