### ISSUE TITLE
Can't view comments in the Tubular app

### ISSUE THREAD

**Issue by MuerteRoja** [polymorphicshade/Tubular#56]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/Tubular/releases/latest).
- [X] I am *not* able to reproduce the bug with the *latest version* of [vanilla NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/Tubular/issues) or [closed](https://github.com/polymorphicshade/Tubular/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the vanilla NewPipe [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.26.1_r3

### Steps to reproduce the bug

Go to a YouTube video and try to view the comments

### Expected behavior

The expected behavior is that comments can be displayed

### Actual behavior

The current behavior is that comments cannot be displayed

### Logs

ㅤ, [18/04/2024 19:04]
-------------------------------------
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get comment id
 at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsInfoItemExtractor.getCommentId(YoutubeCommentsInfoItemExtractor.java:212)
 at org.schabi.newpipe.extractor.comments.CommentsInfoItemsCollector.extract(CommentsInfoItemsCollector.java:24)
 at org.schabi.newpipe.extractor.comments.CommentsInfoItemsCollector.commit(CommentsInfoItemsCollector.java:124)
 at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor$$ExternalSyntheticLambda3.accept(R8$$SyntheticClass:0)
 at j$.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source:2)
 at j$.util.stream.ReferencePipeline$3$1.accept(Unknown Source:10)
 at j$.util.stream.ReferencePipeline$3$1.accept(Unknown Source:10)
 at j$.util.stream.ReferencePipeline$2$1.accept(Unknown Source:12)
 at j$.util.AbstractList$RandomAccessSpliterator.forEachRemaining(Unknown Source:19)
 at j$.util.stream.AbstractPipeline.copyInto(Unknown Source:22)
 at j$.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source:10)
 at j$.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source:0)
 at j$.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source:0)
 at j$.util.stream.AbstractPipeline.evaluate(Unknown Source:34)
 at j$.util.stream.ReferencePipeline.forEach(Unknown Source:5)
 at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.collectCommentsFrom(YoutubeCommentsExtractor.java:263)
 at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.extractComments(YoutubeCommentsExtractor.java:206)
 at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getInitialPage(YoutubeCommentsExtractor.java:58)
 at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:21)
 at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:48)
 at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:29)
 at org.schabi.newpipe.util.ExtractorHelper.lambda$getCommentsInfo$7(ExtractorHelper.java:182)
 at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$60N_-UL7E5eaxFaFO1bZZmnfwM8(ExtractorHelper.java:0)
 at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda3.call(R8$$SyntheticClass:0)
 at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
 at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
 at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
 at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
 at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
 at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5377)
 at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
 at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
 at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
 at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
 at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16013)
 at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
 at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5377)
 at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
 at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)

ㅤ, [18/04/2024 19:04]
at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
 at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
 at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
 at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
 at java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
 at java.lang.Thread.run(Thread.java:1012)
Caused by: org.schabi.newpipe.extractor.exceptions.ParsingException: Unable to get commentId
 at org.schabi.newpipe.extractor.utils.JsonUtils.getValue(JsonUtils.java:36)
 at org.schabi.newpipe.extractor.utils.JsonUtils.getInstanceOf(JsonUtils.java:44)
 at org.schabi.newpipe.extractor.utils.JsonUtils.getString(JsonUtils.java:55)
 at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsInfoItemExtractor.getCommentId(YoutubeCommentsInfoItemExtractor.java:210)
 ... 47 more
-------------------------------------
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get comment text
 at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsInfoItemExtractor.getCommentText(YoutubeCommentsInfoItemExtractor.java:203)
 at org.schabi.newpipe.extractor.comments.CommentsInfoItemsCollector.extract(CommentsInfoItemsCollector.java:29)
 at org.schabi.newpipe.extractor.comments.CommentsInfoItemsCollector.commit(CommentsInfoItemsCollector.java:124)
 at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor$$ExternalSyntheticLambda3.accept(R8$$SyntheticClass:0)
 at j$.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source:2)
 at j$.util.stream.ReferencePipeline$3$1.accept(Unknown Source:10)
 at j$.util.stream.ReferencePipeline$3$1.accept(Unknown Source:10)
 at j$.util.stream.ReferencePipeline$2$1.accept(Unknown Source:12)
 at j$.util.AbstractList$RandomAccessSpliterator.forEachRemaining(Unknown Source:19)
 at j$.util.stream.AbstractPipeline.copyInto(Unknown Source:22)
 at j$.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source:10)
 at j$.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source:0)
 at j$.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source:0)
 at j$.util.stream.AbstractPipeline.evaluate(Unknown Source:34)
 at j$.util.stream.ReferencePipeline.forEach(Unknown Source:5)
 at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsInfoItemExtractor.getAuthorThumbnails(YoutubeCommentsInfoItemExtractor.java:52)
 ... 48 more

### Affected Android/Custom ROM version

Android 12.0

### Affected device model

Xiaomi Redmi 9

### Additional information

In case you see a date and time in the error logs, it is because at first I wanted to use the WhatsApp application as a clipboard to paste the logs and then copy and paste from the computer version, however the number of the characters that I can enter in WhatsApp chats is limited, so I have had to use the Telegram application as a clipboard instead, which unlike Whatsapp does not have this restriction previously mentioned.
![photo_2024-04-18_19-48-08](https://github.com/polymorphicshade/Tubular/assets/126993006/55c6a58a-1b3a-40c4-b5fd-30686a271ecb)
![photo_2024-04-18_19-38-35](https://github.com/polymorphicshade/Tubular/assets/126993006/b0965ba6-a604-483a-92d6-62013e876f15)
Update: In fact, the characters in the error log are so long that, in order to publish this issue on Github, I had to delete part of said log.

**Comment by BurnyBoi** [comment]
This is being tracked in #45

**Comment by polymorphicshade** [comment]
You didn't follow the checklist.
